version: '3.8'

services:
  app:
    build: .
    container_name: amo_app
    volumes:
      - ./data:/app/data
      - ./credentials.json:/app/credentials.json
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/amo_db

  mongo:
    image: mongo:8.0
    container_name: amo_mongo
    restart: always
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express:latest
    container_name: amo_mongo_express
    restart: always
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ADMINUSERNAME=
      - ME_CONFIG_MONGODB_ADMINPASSWORD=
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin

  caddy:
    image: caddy:2
    container_name: amo_caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - app

volumes:
  mongo_data:
  caddy_data:
  caddy_config:
